apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: apps  # deployment namespace
spec:
  type: ClusterIP
  selector:
    app: metrics-api
  ports:
    - port: 5000         # Port exposed by the service
      targetPort: 5000   # Port on the pod/container