# templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    type: local
    location: opt
provisioner: hostpath.csi.k8s.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: "local"