# Simple Nextcloud values
replicaCount: 2

image:
  repository: nextcloud
  tag: "28.0.0-apache"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: cloud.waldhauser.sk
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10G"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

# External database configuration
database:
  type: postgresql
  host: your-postgres-service
  name: nextcloud
  user: nextcloud
  password: changeme

# External Redis configuration  
redis:
  host: your-redis-service
  port: 6379
  password: ""

# Admin user
admin:
  username: admin
  password: changeme

# Storage
persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  accessMode: ReadWriteMany

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"