    - name: Load existing Helm values
      ansible.builtin.slurp:
        src: "{{ helm_chart_path }}/values.yaml"
      register: helmchart_values_raw

    - name: Parse existing values into a fact
      ansible.builtin.set_fact:
        existing_helm_values: "{{ helmchart_values_raw.content | b64decode | from_yaml }}"