---
apiVersion: v1
kind: Namespace
metadata:
  name: waldhauser
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: maintenance-html
#   namespace: waldhauser
# data:
#   index.html: |
#     ...
#
#
# NEW ! please apply configmap directly from file by using command:
#
# WITHOUT RESTARTING:
# kubectl create configmap maintenance-html --from-file=index.html=indexMaintenance.html -n waldhauser --dry-run=client -o yaml | kubectl apply -f -
#
# WITH RESTARTING:
# kubectl create configmap maintenance-html --from-file=index.html=indexMaintenance.html -n waldhauser --dry-run=client -o yaml | kubectl apply -f - && kubectl rollout restart deployment/waldhauser-maintenance -n waldhauser

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldhauser-maintenance
  namespace: waldhauser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waldhauser-maintenance
  template:
    metadata:
      labels:
        app: waldhauser-maintenance
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: maintenance-html
---
apiVersion: v1
kind: Service
metadata:
  name: waldhauser-maintenance
  namespace: waldhauser
spec:
  type: ClusterIP
  selector:
    app: waldhauser-maintenance
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: waldhauser-ingress
  namespace: waldhauser
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: fabrikanazemiaky.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: waldhauser-maintenance
                port:
                  number: 80