apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.storage.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
  storageClassName: {{ .Values.postgresql.storage.class }}