---
# Create the credentials secret with the full connection string
# apiVersion: v1
# kind: Secret
# metadata:
#   name: rabbitmq-secret
#   namespace: computation
# type: Opaque
# data:
#   # base64 encoded: amqps://myuser:mypassword123@rabbitmq.messagebrokers.svc.cluster.local:5671/
#   host: YW1xcHM6Ly9teXVzZXI6bXlwYXNzd29yZDEyM0ByYWJiaXRtcS5tZXNzYWdlYnJva2Vycy5zdmMuY2x1c3Rlci5sb2NhbDo1NjcxLw==
#   tls: ZW5hYmxl  # base64 encoded "enable"
#   # my CA is tls.crt base64encoded
#   ca: [REDACTED -> is base64 of cert]

# or create manually
# kubectl create secret generic rabbitmq-secret \
#   -n computation \
#   --from-literal=host=$(echo "amqps://myuser:mypassword123@rabbitmq.messagebrokers.svc.cluster.local:5671/" | base64) \
#   --from-literal=tls=$(echo "enable" | base64) \
#   --from-literal=ca=$(cat ca.b64)
---
# TriggerAuthentication with proper host + tls
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: computation
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secret
      key: host
    - parameter: tls
      name: rabbitmq-secret
      key: tls
    - parameter: ca
      name: rabbitmq-secret
      key: ca

---
# ScaledJob using the TriggerAuthentication
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: worker-scaledjob
  namespace: computation
spec:
  # --- 1. Scaling behavior ---
  minReplicaCount: 0              # No jobs running when queue is empty
  maxReplicaCount: 10             # Maximum number of concurrent jobs (pods)
  pollingInterval: 15             # Check RabbitMQ every 15 seconds
  successfulJobsHistoryLimit: 2   # Keep only 2 completed job records
  failedJobsHistoryLimit: 2       # Keep only 2 failed job records

  # --- 2. Job execution configuration ---
  jobTargetRef:
    parallelism: 1                # Each job runs one pod at a time
    completions: 1                # One pod completes one calculation
    backoffLimit: 0               # No retries if it fails
    ttlSecondsAfterFinished: 60   # Cleanup job after 60 seconds
    activeDeadlineSeconds: 7200   # Force shutdown after 2 hours = 7200
    template:
      spec:
        restartPolicy: Never
        containers:
          - name: computation-worker
            image: busybox
            command: ["sleep", "180"]
            imagePullPolicy: IfNotPresent
            env: # env vars of the app to-be-autoscaled have to be in same namespace IF from file
              - name: RABBITMQ_HOST
                value: "rabbitmq.messagebrokers.svc.cluster.local"
              - name: TEST_VARIABLE
                value: "supermegatestvariable"
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi

  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp # amqps fails for some reason
        queueName: computation-tasks
        mode: QueueLength
        value: "1"
        vhostName: "/"
      authenticationRef:
        name: rabbitmq-trigger-auth
