apiVersion: batch/v1
kind: Job
metadata:
  name: create-tenant2-site
  namespace: erpnext
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: create-site
        image: frappe/erpnext:v15.87.1
        command:
        - bash
        - -c
        - |
          cd /home/frappe/frappe-bench
          bench new-site tenant2.erp.waldhauser.sk \
            --db-name tenant2_db \
            --db-type mariadb \
            --db-host erpnext-mariadb \
            --db-port 3306 \
            --db-root-username root \
            --db-root-password changeit \
            --admin-password ChangeMe2@123 \
            --mariadb-user-host-login-scope='%'
          bench --site tenant2.erp.waldhauser.sk install-app erpnext
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: erpnext
      restartPolicy: Never
