---
- name: Rolling Update Strategy
  block:
    - name: Display strategy info
      debug:
        msg: |
          ROLLING STRATEGY deployment
          image tag: {{ new_erpnext_image_tag }}
          release name: {{ helm_release_name }}
          namespace: {{ kubernetes_namespace }}
          chart: {{ helm_chart_path }}
    
    - name: Load existing Helm values
      ansible.builtin.slurp:
        src: "{{ helm_chart_path }}/values.yaml"
      register: helmchart_values_raw

    - name: Parse existing values into a fact
      ansible.builtin.set_fact:
        existing_helm_values: "{{ helmchart_values_raw.content | b64decode | from_yaml }}"

    - name: Define the helm values patch
      ansible.builtin.set_fact:
        helm_patch:
          image:
            tag: "{{ new_erpnext_image_tag }}"
          deploymentStrategy:
            type: 
              type: RollingUpdate  # This maps to .Values.deploymentStrategy.type

    # ==================== DEPLOY NEW ENVIRONMENT ====================
    - name: Merge rolling strategy with existing values
      ansible.builtin.set_fact:
        helm_values: "{{ existing_helm_values | combine(helm_patch, recursive=True) }}"

    # ==================== APPLY HELM RELEASE ====================
    - name: Deploy/upgrade ERPNext with rolling strategy
      kubernetes.core.helm:
        name: "{{ helm_release_name }}"
        kubeconfig_path: "{{ kubeconfig }}"
        chart_ref: "{{ helm_chart_path }}"
        release_namespace: "{{ kubernetes_namespace }}"
        values: "{{ helm_values }}"
        state: present
        wait: true
        wait_timeout: 600s
        atomic: true  # Automatically rolls back on failure
      register: helm_release


    # =================== WAIT FOR JOBS ==================
    - name: Wait for all jobs in namespace to complete
      include_tasks: shared/wait-for-jobs.yaml

    # ==================== PING FIRST TENANT ====================
    - name: Ping first tenant until it's available
      ansible.builtin.include_tasks: shared/healthcheck-first-tenant.yaml