apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-deployment
  namespace: cdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdn
  template:
    metadata:
      labels:
        app: cdn
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cdn-storage
          mountPath: /opt/cdn
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: cdn-storage
        persistentVolumeClaim:
          claimName: cdn-pvc
      - name: nginx-config
        configMap:
          name: cdn-nginx-config
