apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
      - name: {{ .Values.nginxName }}
        image: {{ .Values.nginxImage }}
        resources:
          requests:
            memory: {{ .Values.memoryReq }}
            cpu: {{ .Values.cpuReq }}
          limits:
            memory: {{ .Values.memoryLimits }}
            cpu: {{ .Values.cpuLimits }}
        ports:
        - containerPort: {{ .Values.port }}
        volumeMounts:
        - name: {{ .Values.storageName }}
          mountPath: {{ .Values.hostPath }}
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: {{ .Values.storageName }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}
      - name: nginx-config
        configMap:
          name: {{ .Values.configMapName }}
