{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressName }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- if .Values.ingress.nginx }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- else if .Values.ingress.traefik }}
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- end }}
spec:
  ingressClassName: {{ ternary "nginx" "traefik" .Values.ingress.nginx }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.certSecretName }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceName }}
                port:
                  number: 80
{{- end }}
