apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath }}