apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdn-pv
  namespace: cdn
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/cdn