apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.redis.pvName }}
  labels:
    app: redis
spec:
  capacity:
    storage: {{ .Values.redis.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.redis.storage.class }}
  hostPath:
    path: {{ .Values.redis.storage.folder }}
    type: DirectoryOrCreate