apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
  storageClassName: {{ .Values.redis.storage.class }}