apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}