  apiVersion: v1
  kind: Service
  metadata:
    name: "{{ nextcloud_service_name | default(nextcloud_app_name + '-service') }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ nextcloud_app_name }}"
  spec:
    selector:
      app: "{{ nextcloud_app_name }}"
    ports:
      - port: 80
        targetPort: 80
        name: http
    type: ClusterIP