namespace: cdn
appName: cdn-deployment

replicas: 1
label: cdn

nginxName: nginx
nginxImage: nginx:latest

memoryReq: "128Mi"
cpuReq: "128m"
memoryLimits: "256Mi"
cpuLimits: "256m"

certSecretName: cloudflare-origin-tls
configMapName: cdn-nginx-config
serviceName: cdn-service
port: 80
host: cdn.fabrikanazemiaky.eu

ingressName: cdn-ingress
ingress:
  enabled: true
  nginx: true     # or false
  traefik: false  # or true

pvcName: cdn-pvc
pvName: cdn-pv
storageName: cdn-storage
storageSize: "5Gi"
hostPath: /opt/cdn
