apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nextcloud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.database.host | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.database.name | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: NEXTCLOUD_ADMIN_USER
              value: {{ .Values.admin.username | quote }}
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: {{ .Values.admin.password | quote }}
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: {{ .Values.ingress.host | quote }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: REDIS_HOST_PORT
              value: {{ .Values.redis.port | quote }}
            {{- if .Values.redis.password }}
            - name: REDIS_HOST_PASSWORD
              value: {{ .Values.redis.password | quote }}
            {{- end }}
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /status.php
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.ingress.host }}
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /status.php
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.ingress.host }}
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: nextcloud-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "nextcloud.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}